services:
  - type: web
    name: sistema-erp-construccion-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /404.html
        destination: /spa-redirect.html