services:
  - type: web
    name: sistema-erp-construccion-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /**
        name: Cache-Control
        value: no-cache